2025-08-14 09:13:04,525 - INFO - Текст для обработки: 111111
2025-08-14 09:13:04,682 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:13:04,934 - ERROR - Ошибка создания градиента: only length-1 arrays can be converted to Python scalars
2025-08-14 09:13:04,960 - ERROR - Ошибка обработки изображения img\image.png: 'NoneType' object has no attribute 'load'
2025-08-14 09:13:04,964 - INFO - Обработка завершена за 0.44 секунд
2025-08-14 09:13:04,965 - INFO - Успешно обработано: 0, Ошибок: 1
2025-08-14 09:13:29,287 - INFO - Текст для обработки: 1111
2025-08-14 09:13:29,342 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:13:29,619 - ERROR - Ошибка создания градиента: only length-1 arrays can be converted to Python scalars
2025-08-14 09:13:29,678 - ERROR - Ошибка создания градиента: only length-1 arrays can be converted to Python scalars
2025-08-14 09:13:40,283 - INFO - Сохранено: output\image.png
2025-08-14 09:13:40,294 - INFO - Обработка завершена за 11.01 секунд
2025-08-14 09:13:40,294 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:14:02,310 - INFO - Текст для обработки: 111111
2025-08-14 09:14:02,363 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:14:10,471 - INFO - Сохранено: output\image.png
2025-08-14 09:14:10,477 - INFO - Обработка завершена за 8.17 секунд
2025-08-14 09:14:10,478 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:14:42,715 - INFO - Текст для обработки: 11111
2025-08-14 09:14:42,766 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:14:52,103 - INFO - Сохранено: output\image.png
2025-08-14 09:14:52,107 - INFO - Обработка завершена за 9.39 секунд
2025-08-14 09:14:52,107 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:17:38,314 - INFO - Текст для обработки: 111111111111111111111111111111111111
2025-08-14 09:17:38,365 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:17:46,042 - INFO - Сохранено: output\image.png
2025-08-14 09:17:46,046 - INFO - Обработка завершена за 7.73 секунд
2025-08-14 09:17:46,046 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:18:34,479 - INFO - Текст для обработки: Сегодня я вам расскажу про то что у нас появилось нового в нашем Сургутскомм районе, а это пеервод нашего сотрудника!
2025-08-14 09:18:34,530 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:18:42,263 - INFO - Сохранено: output\image.png
2025-08-14 09:18:42,270 - INFO - Обработка завершена за 7.79 секунд
2025-08-14 09:18:42,270 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:21:16,973 - INFO - Текст для обработки: 111
2025-08-14 09:21:17,038 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:21:25,786 - INFO - Сохранено: output\image.png
2025-08-14 09:21:25,792 - INFO - Обработка завершена за 8.82 секунд
2025-08-14 09:21:25,792 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:22:04,145 - INFO - Текст для обработки: 1
2025-08-14 09:22:04,199 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:22:12,131 - INFO - Сохранено: output\image.png
2025-08-14 09:22:12,136 - INFO - Обработка завершена за 7.99 секунд
2025-08-14 09:22:12,136 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:23:07,081 - INFO - Текст для обработки: 11111
2025-08-14 09:23:07,131 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:23:15,063 - INFO - Сохранено: output\image.png
2025-08-14 09:23:15,070 - INFO - Обработка завершена за 7.99 секунд
2025-08-14 09:23:15,071 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:24:05,767 - INFO - Текст для обработки: 111
2025-08-14 09:24:05,819 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:24:13,894 - INFO - Сохранено: output\image.png
2025-08-14 09:24:13,902 - INFO - Обработка завершена за 8.13 секунд
2025-08-14 09:24:13,902 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:24:45,521 - INFO - Текст для обработки: 1111
2025-08-14 09:24:45,566 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:24:53,807 - INFO - Сохранено: output\image.png
2025-08-14 09:24:53,814 - INFO - Обработка завершена за 8.29 секунд
2025-08-14 09:24:53,814 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:25:54,693 - INFO - Текст для обработки: подростки
2025-08-14 09:25:54,792 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:26:02,614 - INFO - Сохранено: output\image.png
2025-08-14 09:26:02,619 - INFO - Обработка завершена за 7.93 секунд
2025-08-14 09:26:02,619 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:26:47,030 - INFO - Текст для обработки: 1111
2025-08-14 09:26:47,080 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:26:55,545 - INFO - Сохранено: output\image.png
2025-08-14 09:26:55,549 - INFO - Обработка завершена за 8.52 секунд
2025-08-14 09:26:55,549 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:27:27,749 - INFO - Текст для обработки: подростки
2025-08-14 09:27:27,797 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:27:35,807 - INFO - Сохранено: output\image.png
2025-08-14 09:27:35,812 - INFO - Обработка завершена за 8.06 секунд
2025-08-14 09:27:35,812 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:31:56,453 - INFO - Текст для обработки: 113213321321321
2025-08-14 09:31:56,507 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:32:07,587 - INFO - Сохранено: output\image_square.png
2025-08-14 09:32:15,914 - INFO - Сохранено: output\image_landscape.png
2025-08-14 09:32:15,928 - INFO - Обработка завершена за 19.47 секунд
2025-08-14 09:32:15,928 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:33:51,908 - INFO - Текст для обработки: 12312313213
2025-08-14 09:33:51,956 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:34:02,649 - INFO - Сохранено: output\image_square.png
2025-08-14 09:34:07,497 - INFO - Сохранено: output\image_landscape.png
2025-08-14 09:34:07,501 - INFO - Обработка завершена за 15.59 секунд
2025-08-14 09:34:07,502 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:35:49,675 - INFO - Текст для обработки: Подростки
2025-08-14 09:35:49,740 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:35:50,420 - ERROR - Ошибка обработки изображения с конфигурацией square: 'max_lines'
2025-08-14 09:35:57,021 - INFO - Сохранено: output\image_landscape.png
2025-08-14 09:35:57,027 - INFO - Обработка завершена за 7.35 секунд
2025-08-14 09:35:57,027 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:36:22,102 - INFO - Текст для обработки: подростки
2025-08-14 09:36:22,171 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:36:31,282 - INFO - Сохранено: output\image_square.png
2025-08-14 09:36:35,816 - INFO - Сохранено: output\image_landscape.png
2025-08-14 09:36:35,821 - INFO - Обработка завершена за 13.72 секунд
2025-08-14 09:36:35,822 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:37:01,691 - INFO - Текст для обработки: ПРивет спегодня в Сургутском раойне такое было вы даже не поверите свои глазам
2025-08-14 09:37:01,742 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:37:11,009 - INFO - Сохранено: output\image_square.png
2025-08-14 09:37:16,515 - INFO - Сохранено: output\image_landscape.png
2025-08-14 09:37:16,521 - INFO - Обработка завершена за 14.83 секунд
2025-08-14 09:37:16,522 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:39:21,322 - INFO - Текст для обработки: 1123123123
2025-08-14 09:39:21,368 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:39:32,395 - INFO - Сохранено: output\image_square.png
2025-08-14 09:39:39,002 - INFO - Сохранено: output\image_landscape.png
2025-08-14 09:39:39,009 - INFO - Обработка завершена за 17.69 секунд
2025-08-14 09:39:39,010 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:40:22,390 - INFO - Текст для обработки: 111111
2025-08-14 09:40:22,433 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:40:22,942 - INFO - Используем оригинальный размер логотипа (180, 181) для square
2025-08-14 09:40:30,536 - INFO - Сохранено: output\image_square.png
2025-08-14 09:40:30,824 - INFO - Изменяем размер логотипа с (180, 181) на (180, 180) для landscape
2025-08-14 09:40:30,825 - INFO - Логотип размещен в позиции (2080, 50) с размером (180, 180)
2025-08-14 09:40:36,050 - INFO - Сохранено: output\image_landscape.png
2025-08-14 09:40:36,058 - INFO - Обработка завершена за 13.67 секунд
2025-08-14 09:40:36,058 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:41:49,308 - INFO - Текст для обработки: 111111111
2025-08-14 09:41:49,372 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:41:50,246 - INFO - Используем оригинальный размер логотипа (180, 181) для square
2025-08-14 09:42:00,400 - INFO - Сохранено: output\image_square.png
2025-08-14 09:42:00,803 - INFO - Изменяем размер логотипа с (180, 181) на (180, 180) для landscape
2025-08-14 09:42:00,805 - INFO - Логотип размещен в позиции (2080, 50) с размером (180, 180)
2025-08-14 09:42:10,020 - INFO - Сохранено: output\image_landscape.png
2025-08-14 09:42:10,031 - INFO - Обработка завершена за 20.72 секунд
2025-08-14 09:42:10,031 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:43:00,671 - INFO - Текст для обработки: ФВРФЫВРФЛВОФРВДФЫв
2025-08-14 09:43:00,736 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:43:01,458 - INFO - Используем оригинальный размер логотипа (180, 181) для square
2025-08-14 09:43:11,858 - INFO - Сохранено: output\image_square.png
2025-08-14 09:43:12,258 - INFO - Изменяем размер логотипа с (180, 181) на (180, 180) для landscape
2025-08-14 09:43:12,263 - INFO - Логотип размещен в позиции (2080, 50) с размером (180, 180)
2025-08-14 09:43:17,006 - INFO - Сохранено: output\image_landscape.png
2025-08-14 09:43:17,016 - INFO - Обработка завершена за 16.34 секунд
2025-08-14 09:43:17,017 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:44:00,616 - INFO - Текст для обработки: 1231233333
2025-08-14 09:44:00,659 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:44:11,849 - INFO - Сохранено: output\image_square.png
2025-08-14 09:44:19,137 - INFO - Сохранено: output\image_landscape.png
2025-08-14 09:44:19,146 - INFO - Обработка завершена за 18.53 секунд
2025-08-14 09:44:19,147 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:49:18,277 - INFO - Текст для обработки: 1111111
2025-08-14 09:49:18,326 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:49:30,173 - INFO - Сохранено: output\image_square.png
2025-08-14 09:49:35,166 - INFO - Сохранено: output\image_landscape.png
2025-08-14 09:49:35,172 - INFO - Обработка завершена за 16.89 секунд
2025-08-14 09:49:35,173 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:55:19,719 - INFO - Текст для обработки: 11142665465656548516516556555654654654812615464588
2025-08-14 09:55:19,803 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:55:31,327 - INFO - Сохранено: output\image_square.png
2025-08-14 09:55:39,275 - INFO - Сохранено: output\image_landscape.png
2025-08-14 09:55:39,284 - INFO - Обработка завершена за 19.56 секунд
2025-08-14 09:55:39,285 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 09:57:01,352 - INFO - Текст для обработки: 111111111111111111111111111111111111111111
2025-08-14 09:57:01,424 - INFO - Найдено изображений для обработки: 1
2025-08-14 09:57:09,255 - INFO - Сохранено: output\image_square.png
2025-08-14 09:57:14,582 - INFO - Сохранено: output\image_landscape.png
2025-08-14 09:57:14,587 - INFO - Обработка завершена за 13.23 секунд
2025-08-14 09:57:14,587 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 10:13:45,324 - INFO - Текст для обработки: 1111111
2025-08-14 10:13:45,394 - INFO - Найдено изображений для обработки: 1
2025-08-14 10:13:57,350 - INFO - Сохранено: output\image_square.png
2025-08-14 10:14:04,940 - INFO - Сохранено: output\image_landscape.png
2025-08-14 10:14:04,951 - INFO - Обработка завершена за 19.63 секунд
2025-08-14 10:14:04,952 - INFO - Успешно обработано: 1, Ошибок: 0
2025-08-14 10:20:33,756 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 10:20:33,759 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 10:20:37,300 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 10:20:37,303 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 10:20:37,709 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 10:20:37,714 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 10:20:41,599 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 10:20:41,606 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 10:20:42,321 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 10:20:42,333 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 10:20:45,818 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 10:20:45,826 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 10:20:46,994 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 10:20:47,010 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 10:20:50,493 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 10:20:50,498 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 10:20:52,658 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 10:20:52,664 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 10:20:56,137 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 10:20:56,141 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 10:21:00,283 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 10:21:00,287 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 10:21:03,984 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 10:21:03,991 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 10:30:42,924 - INFO - Сохранено: output\user_image_square.png
2025-08-14 10:30:47,631 - INFO - Сохранено: output\user_image_landscape.png
2025-08-14 10:34:04,411 - INFO - Сохранено: output\user_image_square.png
2025-08-14 10:34:12,191 - INFO - Сохранено: output\user_image_landscape.png
2025-08-14 10:35:14,750 - INFO - Сохранено: output\user_image_square.png
2025-08-14 10:35:22,146 - INFO - Сохранено: output\user_image_landscape.png
2025-08-14 10:42:13,472 - INFO - Сохранено: output\user_image_square.png
2025-08-14 10:42:21,776 - INFO - Сохранено: output\user_image_landscape.png
2025-08-14 10:51:01,903 - INFO - Сохранено: output\user_image_square.png
2025-08-14 10:51:10,021 - INFO - Сохранено: output\user_image_landscape_center.png
2025-08-14 10:51:18,452 - INFO - Сохранено: output\user_image_landscape_top.png
2025-08-14 10:51:25,979 - INFO - Сохранено: output\user_image_landscape_bottom.png
2025-08-14 10:53:25,605 - INFO - Сохранено: output\user_image_square.png
2025-08-14 10:53:33,880 - INFO - Сохранено: output\user_image_landscape_center.png
2025-08-14 10:53:41,605 - INFO - Сохранено: output\user_image_landscape_top.png
2025-08-14 10:53:46,375 - INFO - Сохранено: output\user_image_landscape_bottom.png
2025-08-14 11:01:24,937 - INFO - Сохранено: output\user_image_square.png
2025-08-14 11:01:28,559 - INFO - Сохранено: output\user_image_landscape_center.png
2025-08-14 11:01:32,232 - INFO - Сохранено: output\user_image_landscape_top.png
2025-08-14 11:01:35,802 - INFO - Сохранено: output\user_image_landscape_bottom.png
2025-08-14 11:06:17,934 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:06:17,939 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:06:21,357 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:06:21,365 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:14:47,395 - INFO - Сохранено: output\user_image_square.png
2025-08-14 11:26:44,216 - INFO - Сохранено: output\user_image_square.png
2025-08-14 11:26:47,726 - INFO - Сохранено: output\user_image_landscape.png
2025-08-14 11:26:52,287 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:26:52,291 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:26:55,689 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:26:55,692 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:26:56,074 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:26:56,076 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:26:59,697 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:26:59,700 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:27:00,341 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:27:00,347 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:27:04,475 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:27:04,481 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:27:04,919 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:27:04,922 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:27:10,080 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:27:10,083 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:27:10,768 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:27:10,771 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:27:14,906 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:27:14,910 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:27:19,034 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:27:19,037 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:29:15,705 - INFO - Сохранено: output\user_image_landscape.png
2025-08-14 11:29:44,575 - INFO - Сохранено: output\user_image_landscape.png
2025-08-14 11:36:21,391 - INFO - Сохранено: output\user_image_landscape_bottom.png
2025-08-14 11:40:11,464 - INFO - Сохранено: output\user_image_landscape_bottom.png
2025-08-14 11:42:36,593 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:42:36,596 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:42:39,985 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:42:39,987 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:42:40,388 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:42:40,392 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:42:44,025 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:42:44,028 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:42:44,654 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:42:44,657 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:42:48,801 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:42:48,805 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:42:49,195 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:42:49,202 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:42:52,583 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:42:52,590 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:42:53,226 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:42:53,231 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:42:56,622 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:42:56,627 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:42:57,770 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:42:57,773 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:43:01,155 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:43:01,162 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:43:03,285 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:43:03,289 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:43:04,806 - INFO - Сохранено: output\user_image_landscape_bottom.png
2025-08-14 11:43:06,672 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:43:06,681 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:43:10,819 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:43:10,823 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:43:14,465 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:43:14,469 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:43:22,608 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:43:22,611 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:43:26,786 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:43:26,790 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:43:42,925 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:43:42,929 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:43:48,075 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:43:48,081 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:44:20,235 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:44:20,241 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:44:23,653 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:44:23,659 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:07,419 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:07,423 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:10,804 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:10,807 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:11,193 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:11,197 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:14,821 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:14,827 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:15,469 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:15,472 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:19,610 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:19,613 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:20,737 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:20,745 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:23,806 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:23,811 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:24,160 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:24,164 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:27,449 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:27,455 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:27,555 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:27,561 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:28,695 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:28,701 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:32,103 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:32,112 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:34,230 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:34,232 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:37,617 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:37,622 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:38,011 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:38,015 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:41,651 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:41,655 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:42,031 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:42,037 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:43,264 - INFO - Сохранено: output\user_image_landscape_bottom.png
2025-08-14 11:45:46,180 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:46,194 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:46,826 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:46,829 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:51,959 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:51,963 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:53,113 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:53,117 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:45:57,258 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:45:57,263 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:46:02,394 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:46:02,397 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:46:10,519 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:46:10,523 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:46:14,642 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:46:14,646 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:46:27,596 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:46:27,598 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:46:30,789 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:46:30,792 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:46:35,725 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:46:35,728 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:47:07,872 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:47:07,878 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:47:11,284 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-14 11:47:11,288 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\ROKA\AppData\Roaming\Python\Python313\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-14 11:50:00,357 - INFO - Выравнивание ландшафта: bottom
2025-08-14 11:50:00,358 - INFO - Применено выравнивание по низу
2025-08-14 11:50:03,286 - INFO - Сохранено: output\user_image_landscape_bottom.png
2025-08-14 11:52:26,445 - INFO - Выравнивание ландшафта: bottom
2025-08-14 11:52:26,446 - INFO - Применено выравнивание по низу
2025-08-14 11:52:30,074 - INFO - Сохранено: output\user_image_landscape_bottom.png
2025-08-14 11:55:07,668 - INFO - Выравнивание ландшафта: bottom
2025-08-14 11:55:07,669 - INFO - Применено выравнивание по низу
2025-08-14 11:55:11,433 - INFO - Сохранено: output\user_image_landscape_bottom.png
2025-08-14 11:57:10,371 - INFO - Выравнивание ландшафта: bottom
2025-08-14 11:57:10,372 - INFO - Применено выравнивание по низу
2025-08-14 11:57:14,191 - INFO - Сохранено: output\user_image_landscape_bottom.png
2025-08-14 12:02:55,859 - INFO - Выравнивание ландшафта: center
2025-08-14 12:02:55,860 - INFO - Применено выравнивание по центру
2025-08-14 12:03:00,156 - INFO - Сохранено: output\user_image_landscape_center.png
2025-08-14 12:03:20,288 - INFO - Выравнивание ландшафта: top
2025-08-14 12:03:20,290 - INFO - Применено выравнивание по верху
2025-08-14 12:03:24,734 - INFO - Сохранено: output\user_image_landscape_top.png
2025-08-14 12:03:53,198 - INFO - Выравнивание ландшафта: bottom
2025-08-14 12:03:53,199 - INFO - Применено выравнивание по низу
2025-08-14 12:03:57,850 - INFO - Сохранено: output\user_image_landscape_bottom.png
